version: '3.3'
services:
  bookmedik:
    container_name: bookmedik-app
    image: afermor8/bookmedik:v2
    restart: always
    environment:
      USUARIO_BOOKMEDIK: admin
      CONTRA_BOOKMEDIK: admin
      DATABASE_HOST: bd_mariadb
      NOMBRE_DB: bookmedik
    ports:
      - 8082:80
    depends_on:
      - db
  db:
    container_name: bd_mariadb
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: bookmedik
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
    mariadb_data:
